version: '3'
services:
  # reactの環境
  react_playground:
    build:
      context: ./Docker/react/
    volumes:
      - ./react_playground:/usr/src/app
    working_dir: /usr/src/app/myapp
    command: "npm start"
    ports:
      - "3000:3000"
    stdin_open: true 
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
  
  react_playground_express:
    build:
      context: ./Docker/express
    volumes:
      - ./react_playground_express:/usr/src/app
    command: "npm start"
    ports:
      - "3001:3001"
    tty: true